/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedVotingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "encryptedVote"
      | "owner"
      | "publishEncryptedTally"
      | "register"
      | "registered"
      | "submitEncryptedVote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TallyPublished" | "VoteSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "encryptedVote",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publishEncryptedTally",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "register", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEncryptedVote",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "encryptedVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publishEncryptedTally",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registered", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitEncryptedVote",
    data: BytesLike
  ): Result;
}

export namespace TallyPublishedEvent {
  export type InputTuple = [ciphertextTally: BytesLike];
  export type OutputTuple = [ciphertextTally: string];
  export interface OutputObject {
    ciphertextTally: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteSubmittedEvent {
  export type InputTuple = [voter: AddressLike];
  export type OutputTuple = [voter: string];
  export interface OutputObject {
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedVoting extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedVoting;
  waitForDeployment(): Promise<this>;

  interface: EncryptedVotingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  encryptedVote: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  publishEncryptedTally: TypedContractMethod<
    [ciphertextTally: BytesLike],
    [void],
    "nonpayable"
  >;

  register: TypedContractMethod<[], [void], "nonpayable">;

  registered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  submitEncryptedVote: TypedContractMethod<
    [ciphertext: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "encryptedVote"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publishEncryptedTally"
  ): TypedContractMethod<[ciphertextTally: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "submitEncryptedVote"
  ): TypedContractMethod<[ciphertext: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "TallyPublished"
  ): TypedContractEvent<
    TallyPublishedEvent.InputTuple,
    TallyPublishedEvent.OutputTuple,
    TallyPublishedEvent.OutputObject
  >;
  getEvent(
    key: "VoteSubmitted"
  ): TypedContractEvent<
    VoteSubmittedEvent.InputTuple,
    VoteSubmittedEvent.OutputTuple,
    VoteSubmittedEvent.OutputObject
  >;

  filters: {
    "TallyPublished(bytes)": TypedContractEvent<
      TallyPublishedEvent.InputTuple,
      TallyPublishedEvent.OutputTuple,
      TallyPublishedEvent.OutputObject
    >;
    TallyPublished: TypedContractEvent<
      TallyPublishedEvent.InputTuple,
      TallyPublishedEvent.OutputTuple,
      TallyPublishedEvent.OutputObject
    >;

    "VoteSubmitted(address)": TypedContractEvent<
      VoteSubmittedEvent.InputTuple,
      VoteSubmittedEvent.OutputTuple,
      VoteSubmittedEvent.OutputObject
    >;
    VoteSubmitted: TypedContractEvent<
      VoteSubmittedEvent.InputTuple,
      VoteSubmittedEvent.OutputTuple,
      VoteSubmittedEvent.OutputObject
    >;
  };
}
